services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    networks:
      - proxy-net

    depends_on:
      - app1
      - app2

  app1:
    build: ./app1
    environment:
      - RAILS_ENV=development
      - RAILS_RELATIVE_URL_ROOT=/app1
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/app1_development
    depends_on:
      - db
    expose:
      - "3000"

    networks:
      proxy-net:
        aliases:
          - app1-web
      koinavi-net:

  app2:
    build: ./app2
    environment:
      - RAILS_ENV=development
      - RAILS_RELATIVE_URL_ROOT=/app2
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/app2_development
    depends_on:
      - db
    networks:
      proxy-net:
        aliases:
          - app2-web
      koinavi-net:


  db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      koinavi-net:
volumes:
  db_data:
networks:
  proxy-net:
    external: true

  # koinavi 内部用（自動作成されるので docker network create 不要）
  koinavi-net:
    driver: bridge


